"""empty message

Revision ID: 622be1aa5354
Revises: 0c39b1466869
Create Date: 2023-05-12 18:24:41.931559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622be1aa5354'
down_revision = '0c39b1466869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('img_1',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.drop_column('img_4')
        batch_op.drop_column('img_2')
        batch_op.drop_column('img_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_3', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('img_2', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('img_4', sa.BLOB(), nullable=True))
        batch_op.alter_column('img_1',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
